---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    nfs.io/storage-path: wordpress
  name: pv-claim-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storage_class }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage_size }}
