---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "wordpress.fullname" . }}-config
  namespace: default
spec:
  encryptedData:
    wp-config.php: {{ .Values.wp.config }}
  template:
    metadata:
      name: {{ include "wordpress.fullname" . }}-config
      namespace: default
    type: Opaque
